### ISSUE TITLE
Use a testing framework

### ISSUE THREAD

**Issue by CGA1123** [codervault/codervault#1]
It would be good to start adding tests to this.

**Comment by mrvncaragay** [comment]
Hi, im new to contributing but i would like to contribute to this project. 

I can use rspec and factorygirl to start testing models. would that be an ok approach?

**Comment by CGA1123** [comment]
Yeah, that would be good, as long as @SalGnt is ok with it?

**Comment by CGA1123** [comment]
This is being worked on in #4

**Comment by SalGnt** [comment]
I'm totally fine with this, I'm new to Rails and I never used a testing framework.
